// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file test/schemaregistry/serde/widget.proto (package test, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test/schemaregistry/serde/widget.proto.
 */
export const file_test_schemaregistry_serde_widget: GenFile = /*@__PURE__*/
  fileDesc("CiZ0ZXN0L3NjaGVtYXJlZ2lzdHJ5L3NlcmRlL3dpZGdldC5wcm90bxIEdGVzdCI1CgZXaWRnZXQSDAoEbmFtZRgBIAEoCRIMCgRzaXplGAIgASgFEg8KB3ZlcnNpb24YAyABKAVCCVoHLi4vdGVzdGIGcHJvdG8z");

/**
 * @generated from message test.Widget
 */
export type Widget = Message<"test.Widget"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 size = 2;
   */
  size: number;

  /**
   * @generated from field: int32 version = 3;
   */
  version: number;
};

/**
 * Describes the message test.Widget.
 * Use `create(WidgetSchema)` to create a new message.
 */
export const WidgetSchema: GenMessage<Widget> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_widget, 0);

