// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file test/schemaregistry/serde/newerwidget.proto (package test, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test/schemaregistry/serde/newerwidget.proto.
 */
export const file_test_schemaregistry_serde_newerwidget: GenFile = /*@__PURE__*/
  fileDesc("Cit0ZXN0L3NjaGVtYXJlZ2lzdHJ5L3NlcmRlL25ld2Vyd2lkZ2V0LnByb3RvEgR0ZXN0IjwKC05ld2VyV2lkZ2V0EgwKBG5hbWUYASABKAkSDgoGbGVuZ3RoGAIgASgFEg8KB3ZlcnNpb24YAyABKAVCCVoHLi4vdGVzdGIGcHJvdG8z");

/**
 * @generated from message test.NewerWidget
 */
export type NewerWidget = Message<"test.NewerWidget"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 length = 2;
   */
  length: number;

  /**
   * @generated from field: int32 version = 3;
   */
  version: number;
};

/**
 * Describes the message test.NewerWidget.
 * Use `create(NewerWidgetSchema)` to create a new message.
 */
export const NewerWidgetSchema: GenMessage<NewerWidget> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_newerwidget, 0);

