// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file test/schemaregistry/serde/newwidget.proto (package test, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test/schemaregistry/serde/newwidget.proto.
 */
export const file_test_schemaregistry_serde_newwidget: GenFile = /*@__PURE__*/
  fileDesc("Cil0ZXN0L3NjaGVtYXJlZ2lzdHJ5L3NlcmRlL25ld3dpZGdldC5wcm90bxIEdGVzdCI6CglOZXdXaWRnZXQSDAoEbmFtZRgBIAEoCRIOCgZoZWlnaHQYAiABKAUSDwoHdmVyc2lvbhgDIAEoBUIJWgcuLi90ZXN0YgZwcm90bzM");

/**
 * @generated from message test.NewWidget
 */
export type NewWidget = Message<"test.NewWidget"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 height = 2;
   */
  height: number;

  /**
   * @generated from field: int32 version = 3;
   */
  version: number;
};

/**
 * Describes the message test.NewWidget.
 * Use `create(NewWidgetSchema)` to create a new message.
 */
export const NewWidgetSchema: GenMessage<NewWidget> = /*@__PURE__*/
  messageDesc(file_test_schemaregistry_serde_newwidget, 0);

