// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file confluent/types/decimal.proto (package confluent.type, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file confluent/types/decimal.proto.
 */
export const file_confluent_types_decimal: GenFile = /*@__PURE__*/
  fileDesc("Ch1jb25mbHVlbnQvdHlwZXMvZGVjaW1hbC5wcm90bxIOY29uZmx1ZW50LnR5cGUiOgoHRGVjaW1hbBINCgV2YWx1ZRgBIAEoDBIRCglwcmVjaXNpb24YAiABKA0SDQoFc2NhbGUYAyABKAVCCloILi4vdHlwZXNiBnByb3RvMw");

/**
 * @generated from message confluent.type.Decimal
 */
export type Decimal = Message<"confluent.type.Decimal"> & {
  /**
   * The two's-complement representation of the unscaled integer value in big-endian byte order
   *
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;

  /**
   * The precision
   *
   * @generated from field: uint32 precision = 2;
   */
  precision: number;

  /**
   * The scale
   *
   * @generated from field: int32 scale = 3;
   */
  scale: number;
};

/**
 * Describes the message confluent.type.Decimal.
 * Use `create(DecimalSchema)` to create a new message.
 */
export const DecimalSchema: GenMessage<Decimal> = /*@__PURE__*/
  messageDesc(file_confluent_types_decimal, 0);

