if (CPACK_GENERATOR STREQUAL NuGet)
  message("Copying ${CMAKE_CURRENT_LIST_DIR}/${CPACK_NUGET_TARGETS_FILE} to ${CPACK_STAGING_DIR}/${CPACK_PACKAGE_NAME}.targets for inclusion into NuGet package")
  file(INSTALL DESTINATION "${CPACK_STAGING_DIR}" TYPE FILE
    RENAME "${CPACK_PACKAGE_NAME}.targets"
    FILES "${CMAKE_CURRENT_LIST_DIR}/${CPACK_NUGET_TARGETS_FILE}")
endif()
