#!/usr/bin/env perl
#

#
# Generate linker script to only expose symbols of the public API
#

@funcs = ();
while (<>) {
    push(@funcs, $2) if /^(\S+.*\s+\**)?(rd_kafka_\S+)\s+\(/;
}


print "# Automatically generated by lds-gen.pl - DO NOT EDIT\n";
print "{\n global:\n";
if (scalar @funcs == 0) {
    print "    *;\n";
} else {
    foreach my $f (sort @funcs) {
        print "    $f;\n";
    }

    print " local:\n    *;\n";
}

print "};\n";

