# Makefile.schemaregistry

# Variables
NODE ?= node
ESLINT ?= ./node_modules/.bin/eslint
JEST ?= ./node_modules/.bin/jest
TS_NODE ?= ./node_modules/.bin/ts-node

# Paths
SRC_DIR = schemaregistry
TEST_DIR = test/schemaregistry
INTEG_DIR = e2e/schemaregistry

# Tasks
.PHONY: all lint test integtest

all: lint test

lint:
	$(ESLINT) $(SRC_DIR) $(TEST_DIR) $(INTEG_DIR)

test:
	$(JEST) $(TEST_DIR)

integtest:
	$(JEST) $(INTEG_DIR)