meta:
  name: low_latency
  description: "Minimize end-to-end latency — no batching, no linger, single-partition"

workload:
  msg_count: 100000
  msg_size: 128
  num_partitions: 1
  replication_factor: 1
  topic_name: null
  topic_auto_delete: true
  compression: none

producer:
  acks: "1"
  linger_ms: 0
  batch_size: 1
  batch_num_messages: 1
  queue_buffering_max_messages: 1
  queue_buffering_max_kbytes: 1024
  message_send_max_retries: 3
  retry_backoff_ms: 100
  enable_idempotence: false
  transactional_id: null
  transaction_timeout_ms: 60000
  extra_config:
    socket.nagle.disable: "true"

consumer:
  group_id: null
  auto_offset_reset: earliest
  fetch_min_bytes: 1
  fetch_wait_max_ms: 0
  queued_min_messages: 1
  session_timeout_ms: 10000
  max_poll_interval_ms: 300000
  enable_auto_commit: true
  extra_config: {}

timeouts:
  producer_timeout_sec: 60
  consumer_timeout_sec: 90
  consumer_catchup_grace_sec: 30
