{
 "title": "librdkafka dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance_variable_name", "query": "instance" },
   { "name": "brokers_variable_name", "query": "broker" },
   { "name": "topics_variable_name", "query": "topic" },
   { "name": "partitions_variable_name", "query": "partition" },
   { "name": "node_variable_name", "query": "kubernetes_pod_name" },
   { "name": "value_variable_name", "query": "value" },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "query_result(last_over_time(librdkafka_name[$__range]))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(librdkafka_name{$node_variable_name=~\"$node_name\"}[$__range]))"
    }
   },
   {
    "name": "brokers",
    "label": "Brokers",
    "query": {
     "query": "query_result(last_over_time(librdkafka_brokers_name{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__range]))"
    }
   },
   {
    "name": "topics",
    "label": "Topics",
    "query": {
     "query": "query_result(last_over_time(librdkafka_topics_topic{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__range]))"
    }
   },
   {
    "name": "partitions",
    "label": "Partitions",
    "query": {
     "query": "query_result(last_over_time(librdkafka_topics_partitions_partition{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "tx/s",
   "type": "timeseries",
   "description": "Total number of requests sent to Kafka brokers",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_tx{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name))",
     "legendFormat": "tx/s {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "tx_bytes/s",
   "type": "timeseries",
   "description": "Total number of bytes transmitted to Kafka brokers",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_tx_bytes{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name))",
     "legendFormat": "tx_bytes/s {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "rx/s",
   "type": "timeseries",
   "description": "Total number of responses received from Kafka brokers",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_rx{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name))",
     "legendFormat": "rx/s {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "rx_bytes/s",
   "type": "timeseries",
   "description": "Total number of bytes received from Kafka brokers",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_rx_bytes{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name))",
     "legendFormat": "rx_bytes/s {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "txmsgs/s",
   "type": "timeseries",
   "description": "Total number of messages transmitted (produced) to Kafka brokers",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_txmsgs{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name))",
     "legendFormat": "txmsgs/s {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "txmsg_bytes/s",
   "type": "timeseries",
   "description": "Total number of message bytes (including framing, such as per-Message framing and MessageSet/batch framing) transmitted to Kafka brokers",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_txmsg_bytes{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name))",
     "legendFormat": "txmsg_bytes/s {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "msg_cnt",
   "type": "timeseries",
   "description": "Current number of messages in producer queues",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_msg_cnt{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"})",
     "legendFormat": "msg_cnt {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "msg_max",
   "type": "timeseries",
   "description": "Threshold: maximum number of messages allowed allowed on the producer queues",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_msg_max{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"})",
     "legendFormat": "msg_max {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "msg_size",
   "type": "timeseries",
   "description": "Current total size of messages in producer queues",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_msg_size{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"})",
     "legendFormat": "msg_size {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "msg_size_max",
   "type": "timeseries",
   "description": "Threshold: maximum total size of messages allowed on the producer queues",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_msg_size_max{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"})",
     "legendFormat": "msg_size {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "rxmsgs/s",
   "type": "timeseries",
   "description": "Total number of messages consumed, not including ignored messages (due to offset, etc), from Kafka brokers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_rxmsgs{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name))",
     "legendFormat": "rxmsgs/s {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "rxmsg_bytes/s",
   "type": "timeseries",
   "description": "Total number of message bytes (including framing) received from Kafka brokers",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_rxmsg_bytes{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name))",
     "legendFormat": "rxmsg_bytes/s {node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "consumer_lag_stored",
   "type": "timeseries",
   "description": "consumer_lag_stored, difference between (hi_offset or ls_offset) and stored_offset",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_topics_partitions_consumer_lag_stored{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\", $partitions_variable_name=~\"$partitions\"} >= 0)",
     "legendFormat": "consumer_lag_stored {topic={{topic}}, partition={{partition}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "fetchq_cnt",
   "type": "timeseries",
   "description": "fetchq_cnt: number of pre-fetched messages in fetch queue",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_topics_partitions_fetchq_cnt{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\", $partitions_variable_name=~\"$partitions\"})",
     "legendFormat": "fetchq_cnt {topic={{topic}}, partition={{partition}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "fetchq_size",
   "type": "timeseries",
   "description": "fetchq_size: bytes in fetchq",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_topics_partitions_fetchq_size{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\", $partitions_variable_name=~\"$partitions\"})",
     "legendFormat": "fetchq_size {topic={{topic}}, partition={{partition}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  { "title": "Brokers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "tx/s",
   "type": "timeseries",
   "description": "Total number of requests sent",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_brokers_tx{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name, $brokers_variable_name))",
     "legendFormat": "tx/s {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "txbytes/s",
   "type": "timeseries",
   "description": "Total number of bytes sent",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_brokers_txbytes{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name, $brokers_variable_name))",
     "legendFormat": "txbytes/s {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "rtt_max",
   "type": "timeseries",
   "description": "Broker latency / round-trip time in microseconds.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_brokers_rtt_max{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"})",
     "legendFormat": "rtt_max {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "rx/s",
   "type": "timeseries",
   "description": "Total number of responses received",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_brokers_rx{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name, $brokers_variable_name))",
     "legendFormat": "rx/s {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "rxbytes/s",
   "type": "timeseries",
   "description": "Total number of bytes received",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_brokers_rxbytes{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name, $brokers_variable_name))",
     "legendFormat": "rxbytes/s {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "int_latency",
   "type": "timeseries",
   "description": "Internal producer queue latency in microseconds.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_brokers_int_latency_max{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"})",
     "legendFormat": "int_latency_max {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "connects",
   "type": "timeseries",
   "description": "Number of connection attempts, including successful and failed, and name resolution failures.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_brokers_connects{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"})",
     "legendFormat": "brokers_connects {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "disconnects",
   "type": "timeseries",
   "description": "Number of disconnects (triggered by broker, network, load-balancer, etc.).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_brokers_disconnects{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"})",
     "legendFormat": "brokers_disconnects {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "outbuf_latency",
   "type": "timeseries",
   "description": " Internal request queue latency in microseconds. This is the time between a request is enqueued on the transmit (outbuf).",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_brokers_outbuf_latency_max{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $brokers_variable_name=~\"$brokers\"})",
     "legendFormat": "outbuf_latency_max {broker={{broker}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "batchcnt",
   "type": "timeseries",
   "description": "Batch message counts",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_topics_batchcnt_avg{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\"})",
     "legendFormat": "batchcnt_avg {topic={{topic}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    },
    {
     "expr": "sort_desc(librdkafka_topics_batchcnt_min{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\"})",
     "legendFormat": "batchcnt_min {topic={{topic}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    },
    {
     "expr": "sort_desc(librdkafka_topics_batchcnt_max{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\"})",
     "legendFormat": "batchcnt_max {topic={{topic}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "batchsize",
   "type": "timeseries",
   "description": "Batch sizes in bytes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(librdkafka_topics_batchsize_avg{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\"})",
     "legendFormat": "batchsize_avg {topic={{topic}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    },
    {
     "expr": "sort_desc(librdkafka_topics_batchsize_min{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\"})",
     "legendFormat": "batchsize_min {topic={{topic}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    },
    {
     "expr": "sort_desc(librdkafka_topics_batchsize_max{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\"})",
     "legendFormat": "batchsize_max {topic={{topic}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  { "title": "Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "txmsgs/s",
   "type": "timeseries",
   "description": "Total number of messages transmitted (produced)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_topics_partitions_txmsgs{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\", $partitions_variable_name=~\"$partitions\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name, $topics_variable_name, $partitions_variable_name))",
     "legendFormat": "txmsgs/s {topic={{topic}}, partition={{partition}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "txbytes/s",
   "type": "timeseries",
   "description": "Total number of bytes transmitted for txmsgs",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_topics_partitions_txbytes{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\", $partitions_variable_name=~\"$partitions\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name, $topics_variable_name, $partitions_variable_name))",
     "legendFormat": "txbytes/s {topic={{topic}}, partition={{partition}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "rxmsgs/s",
   "type": "timeseries",
   "description": "Total number of messages consumed, not including ignored messages (due to offset, etc).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_topics_partitions_rxmsgs{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\", $partitions_variable_name=~\"$partitions\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name, $topics_variable_name, $partitions_variable_name))",
     "legendFormat": "rxmsgs/s {topic={{topic}}, partition={{partition}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  },
  {
   "title": "rxbytes/s",
   "type": "timeseries",
   "description": "Total number of bytes received for rxmsgs",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(max(irate(librdkafka_topics_partitions_rxbytes{$node_variable_name=~\"$node_name\", $instance_variable_name=~\"$instance\", $topics_variable_name=~\"$topics\", $partitions_variable_name=~\"$partitions\"}[$__rate_interval])) by ($node_variable_name, $instance_variable_name, $topics_variable_name, $partitions_variable_name))",
     "legendFormat": "rxbytes/s {topic={{topic}}, partition={{partition}}, node={{$node_variable_name}}, instance={{$instance_variable_name}}}"
    }
   ]
  }
 ]
}